package com.example.xiangqi.ui;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import android.view.View;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import com.example.xiangqi.R;
import com.example.xiangqi.ai.MinimaxAI;
import com.example.xiangqi.core.Board;
import com.example.xiangqi.core.Move;
import com.example.xiangqi.core.Piece;

import java.util.ArrayList;
import java.util.List;

public class GameActivity extends AppCompatActivity implements BoardView.MoveListener {

    private BoardView boardView;
    private Board board;
    private MinimaxAI ai;
    private boolean isPve;
    private boolean isRedTurn = true;
    private boolean isGameOver = false;
    private TextView statusText;

    // For replay
    private boolean isReplaying = false;
    private List<Move> replayHistory;
    private int replayIndex = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_game);

        isPve = getIntent().getBooleanExtra("IS_PVE", false);

        boardView = findViewById(R.id.board_view);
        statusText = findViewById(R.id.status_text);

        board = new Board();
        boardView.setBoard(board);
        boardView.setMoveListener(this);

        if (isPve) {
            ai = new MinimaxAI(3); // Default difficulty
            showDifficultyDialog();
        }

        findViewById(R.id.btn_undo).setOnClickListener(v -> undo());
        findViewById(R.id.btn_replay).setOnClickListener(v -> startReplay());

        updateStatus();
    }

    private void showDifficultyDialog() {
        String[] levels = { "Easy", "Medium", "Hard" };
        new AlertDialog.Builder(this)
                .setTitle("Select Difficulty")
                .setItems(levels, (dialog, which) -> {
                    if (ai != null)
                        ai.setDifficulty(which + 1);
                })
                .setCancelable(false)
                .show();
    }

    @Override
    public void onMoveAttempt(int startX, int startY, int endX, int endY) {
        if (isGameOver || isReplaying)
            return;

        Piece p = board.getPiece(startX, startY);
        if (p == null || p.isRed != isRedTurn) {
            // Cannot move empty or opponent piece
            // But if user tapped opponent piece as capture target, that's handled by
            // BoardView logic (Move attempt is from selected to target)
            // Here startX/Y is the selected piece. So if selected piece is wrong turn,
            // ignore.
            return;
        }

        // Validate Move
        // We need to check if the move is in the list of legal moves generated by Board
        List<Move> validMoves = board.generateLegalMoves(isRedTurn);
        Move moveToDo = null;
        for (Move m : validMoves) {
            if (m.startX == startX && m.startY == startY && m.endX == endX && m.endY == endY) {
                moveToDo = m;
                break;
            }
        }

        if (moveToDo != null) {
            makeMove(moveToDo);

            if (isPve && !isGameOver && !isRedTurn) {
                // Computer Turn
                boardView.setInteractionEnabled(false);
                new Thread(() -> {
                    Move aiMove = ai.getBestMove(board, false);
                    new Handler(Looper.getMainLooper()).post(() -> {
                        if (aiMove != null) {
                            makeMove(aiMove);
                        } else {
                            // AI has no moves -> Loss for AI (Win for Red)
                            gameEnd(true);
                        }
                        boardView.setInteractionEnabled(true);
                    });
                }).start();
            }
        } else {
            Toast.makeText(this, "Invalid Move", Toast.LENGTH_SHORT).show();
        }
    }

    private void makeMove(Move move) {
        board.executeMove(move);
        isRedTurn = !isRedTurn;
        boardView.invalidate();
        updateStatus();

        checkGameState();
    }

    private void checkGameState() {
        List<Move> moves = board.generateLegalMoves(isRedTurn);
        if (moves.isEmpty()) {
            gameEnd(!isRedTurn); // Current player has no moves -> Loses
        }
    }

    private void gameEnd(boolean redWins) {
        isGameOver = true;
        String msg = redWins ? "Red Wins!" : "Black Wins!";
        statusText.setText(msg);
        new AlertDialog.Builder(this)
                .setMessage(msg)
                .setPositiveButton("OK", null)
                .show();
    }

    private void undo() {
        if (isReplaying)
            return;
        if (board.getHistory().isEmpty())
            return;

        if (isPve) {
            // Undo twice
            board.undoMove(); // Undo AI
            if (!board.getHistory().isEmpty()) {
                board.undoMove(); // Undo Player
            }
            isRedTurn = true; // AI is block so undoing brings back to Red
            isGameOver = false;
        } else {
            board.undoMove();
            isRedTurn = !isRedTurn;
            isGameOver = false;
        }
        boardView.invalidate();
        updateStatus();
    }

    private void startReplay() {
        if (board.getHistory().isEmpty() && !isReplaying)
            return;

        if (!isReplaying) {
            replayHistory = new ArrayList<>(board.getHistory());
            board.reset(); // Effectively clears board and history
            boardView.setBoard(board); // Re-bind
            isReplaying = true;
            replayIndex = 0;
            isRedTurn = true; // Red always starts
            isGameOver = false; // Reset game over state for display
            boardView.setInteractionEnabled(false);

            new AlertDialog.Builder(this)
                    .setTitle("Replay Mode")
                    .setMessage("Tap Next to step through moves.")
                    .setPositiveButton("Next", (d, w) -> nextReplayMove())
                    .setNegativeButton("Exit Replay", (d, w) -> stopReplay())
                    .setNeutralButton("Auto Play", (d, w) -> autoReplay())
                    .show();
        }
    }

    private void nextReplayMove() {
        if (!isReplaying)
            return;
        if (replayIndex < replayHistory.size()) {
            Move m = replayHistory.get(replayIndex++);
            board.executeMove(m); // This pushes to internal history, which is fine
            boardView.invalidate();

            // Show dialog again
            new AlertDialog.Builder(this)
                    .setTitle("Replay Mode")
                    .setPositiveButton("Next", (d, w) -> nextReplayMove())
                    .setNegativeButton("Exit Replay", (d, w) -> stopReplay())
                    .show();
        } else {
            Toast.makeText(this, "Replay Finished", Toast.LENGTH_SHORT).show();
            stopReplay();
        }
    }

    private void autoReplay() {
        // Simple loop with delay
        if (!isReplaying)
            return;
        new Thread(() -> {
            while (replayIndex < replayHistory.size() && isReplaying) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                }

                final Move m = replayHistory.get(replayIndex++);
                new Handler(Looper.getMainLooper()).post(() -> {
                    board.executeMove(m);
                    boardView.invalidate();
                });
            }
            new Handler(Looper.getMainLooper()).post(this::stopReplay);
        }).start();
    }

    private void stopReplay() {
        if (!isReplaying)
            return;
        isReplaying = false;
        // Restore game state? Or just reset?
        // Usually Replay ends cleanly.
        Toast.makeText(this, "Exited Replay Mode", Toast.LENGTH_SHORT).show();
        boardView.setInteractionEnabled(true);
        // Reset to initial state for new game
        board.reset();
        isRedTurn = true;
        boardView.invalidate();
    }

    private void updateStatus() {
        if (!isGameOver) {
            statusText.setText(isRedTurn ? "Red's Turn" : "Black's Turn");
        }
    }
}
